### ISSUE TITLE
Crash when a player in web is hit by a spider

### ISSUE THREAD

**Issue by Fantomrat** [12emin34/GetWebbed#1]
```
java.lang.NoSuchFieldError: Class net.minecraft.class_1294 does not have member field 'net.minecraft.class_1291 field_5919'
	at me._12emin34.getwebbed.GetWebbed.onHurt(GetWebbed.java:33)
	at net.minecraft.class_1657.handler$zcc001$architectury$hurt(class_1657.java:3413)
	at net.minecraft.class_1657.method_5643(class_1657.java)
	at net.minecraft.class_3222.method_5643(class_3222.java:809)
	at net.minecraft.class_1308.method_6121(class_1308.java:1571)
	at net.minecraft.class_1366.method_6288(class_1366.java:151)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:112)
	at net.minecraft.class_1355.method_6275(class_1355.java:103)
	at net.minecraft.class_1308.method_6023(class_1308.java:830)
	at net.minecraft.class_1309.method_6007(class_1309.java:2789)
	at net.minecraft.class_1308.method_6007(class_1308.java:603)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1309.method_5773(class_1309.java:2529)
	at net.minecraft.class_1308.method_5773(class_1308.java:377)
	at net.minecraft.class_1628.method_5773(class_1628.java:85)
	at net.minecraft.class_3218.method_18762(class_3218.java:769)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_3218.method_31420(class_3218.java:407)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:371)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:998)
	at net.minecraft.class_3176.method_3813(class_3176.java:294)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
[crash-2024-06-13_22.51.50-server.txt](https://github.com/user-attachments/files/15823632/crash-2024-06-13_22.51.50-server.txt)

**Comment by 12emin34** [comment]
thank you for the report, I'll be fixing this shortly

**Comment by 12emin34** [comment]
fixed in the latest commit
